CREATE TABLE STUDENT(
   		    STUDENTRNO INT PRIMARY KEY     NOT NULL,
                    STUDENTNAME           VARCHAR(50) NOT NULL,
                    STUDENTAGE            INT     NOT NULL,
                    STUDENTADDRESS        VARCHAR(50)
                    );
                 
INSERT INTO STUDENT (STUDENTRNO,STUDENTNAME,STUDENTAGE,STUDENTADDRESS) VALUES (401, 'Akshay Anchan', 17, 'Udupi');
INSERT INTO STUDENT (STUDENTRNO,STUDENTNAME,STUDENTAGE,STUDENTADDRESS) VALUES (402, 'Akshay k', 46, 'Mangalore');



SELECT STUDENTRNO, STUDENTNAME FROM STUDENT;
UPDATE STUDENT SET STUDENTAGE = 23 WHERE STUDENTRNO = 402;
DELETE FROM STUDENT WHERE ID = 401;

